version: '3.7'

services:
    fakesandmocks:
        container_name: rimutec-fakesandmocks-dev
        build:
            context: .
        working_dir: /app
        volumes:
            - ..:/app:cached
        command: >
            bash -c "pwsh /app/dev/setversion.ps1 && sleep infinity"
